GET http://localhost:5204/api/imc/listar
###
GET http://localhost:5204/api/alunos/listar

###
POST http://localhost:5204/api/alunos/cadastrar
Content-Type: application/json

{
  "nome": "Darci de Souza",
  "dataNasc": "1968/03/06"
}

###
POST http://localhost:5204/api/imc/cadastrar/6
Content-Type: application/json

{
  "altura": 1.60,
  "peso": 65.3
}

###
GET http://localhost:5204/api/imc/listar/6

###
GET http://localhost:5204/api/imc/listar
###
PUT  http://localhost:5204/api/alterar/imc/11
Content-Type: application/json

{
  "altura": 1.80,
  "peso": 67.400
}